version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/python:3.11.3-browsers
    working_directory: ~/CircleCIWork

orbs:
  slack: circleci/slack@4.12.5
  codecov: codecov/codecov@3.2.5

commands:
  notify_success_slack:
    steps:
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "text": ":tada: ${CIRCLE_JOB} ジョブが成功しました。",
                    "emoji": true
                  },
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repogitory*:\n${CIRCLE_PROJECT_REPONAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n${CIRCLE_BRANCH}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commiter*:\n${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*SHA*:\n${CIRCLE_SHA1}"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                    "alt_text": "CircleCI logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

  notify_fail_slack:
    steps:
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "⚠ *${CIRCLE_JOB}* ジョブが失敗しました。"
                  },
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repogitory*:\n${CIRCLE_PROJECT_REPONAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n${CIRCLE_BRANCH}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commiter*:\n${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*SHA*:\n${CIRCLE_SHA1}"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                    "alt_text": "CircleCI logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }

  sparse:
    steps:
      - run:
          name: Sparse checkout
          command: |
            mkdir ~/git_sparse
            cd ~/git_sparse
            git init
            git remote add origin https://github.com/mozkzki/${CIRCLE_PROJECT_REPONAME}.git
            git config core.sparsecheckout true
            echo "poetry.lock" > .git/info/sparse-checkout
            echo "pyproject.toml" >> .git/info/sparse-checkout
            git pull --depth=1 origin ${CIRCLE_BRANCH}
            cd ..
            ls -al ~/git_sparse

  restore:
    steps:
      - when:
          condition:
            matches: { pattern: "^renovate.+$", value: << pipeline.git.branch >> }
          steps:
            - restore_cache:
                key: key-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "~/git_sparse/pyproject.toml" }}
      - unless:
          condition:
            matches: { pattern: "^renovate.+$", value: << pipeline.git.branch >> }
          steps:
            - restore_cache:
                key: key-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "~/git_sparse/poetry.lock" }}

  save:
    steps:
      - when:
          condition:
            matches: { pattern: "^renovate.+$", value: << pipeline.git.branch >> }
          steps:
            - save_cache:
                paths:
                  - "."
                key: key-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "~/git_sparse/pyproject.toml" }}
      - unless:
          condition:
            matches: { pattern: "^renovate.+$", value: << pipeline.git.branch >> }
          steps:
            - save_cache:
                paths:
                  - "."
                key: key-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "~/git_sparse/poetry.lock" }}

jobs:

  setup:
    executor: my-executor
    steps:
      - sparse
      - restore
      - checkout
      - when:
          condition:
            matches: { pattern: "^renovate.+$", value: << pipeline.git.branch >> }
          steps:
            - run:
                name: Install for resolve dependency
                command: |
                  pwd
                  whoami
                  python --version
                  poetry --version
                  poetry config virtualenvs.path ${CIRCLE_WORKING_DIRECTORY}
                  poetry update
            - save
            - store_artifacts:
                path: ./poetry.lock
            - notify_fail_slack
      - unless:
          condition:
            matches: { pattern: "^renovate.+$", value: << pipeline.git.branch >> }
          steps:
            - run:
                name: Install
                command: |
                  pwd
                  whoami
                  python --version
                  poetry --version
                  poetry config virtualenvs.path ${CIRCLE_WORKING_DIRECTORY}
                  poetry install
            - save
            - notify_fail_slack

  lint:
    executor: my-executor
    steps:
      - sparse
      - restore
      - checkout
      - run:
          name: Lint
          command: |
            source $(find . -name ${CIRCLE_PROJECT_REPONAME}*)/bin/activate
            make lint
      - notify_fail_slack


  test:
    executor: my-executor
    steps:
      - sparse
      - restore
      - checkout
      - run:
          name: Test
          command: |
            source $(find . -name ${CIRCLE_PROJECT_REPONAME}*)/bin/activate
            make ut
      - codecov/upload
      - store_artifacts:
          path: ./image.png
      - notify_success_slack
      - notify_fail_slack

workflows:
  version: 2.1
  build-and-test-workflow:
    jobs:
      - setup:
          context: ci
      - lint:
          requires:
            - setup
          context: ci
      - test:
          requires:
            - lint
          context: ci
